### ISSUE TITLE
Role overwrites gerrlingguy.php's php_packages

### ISSUE THREAD

**Issue by socketwench** [geerlingguy/ansible-role-php-versions#13]
## Description

When using this role, the php_packages variable is completely overridden by the role's defaults. 

For example, this is in my group_vars:

```
php_packages:
  - php
  - php-fpm
  - php-cli
  - php7.1-common
  - php-gd
  - php-mbstring
  - php-xml
  - php-memcached
  - php7.1-opcache
  - php-sqlite3
  - php7.1-mysql
  - php7.1-curl
```

When using this role, however, the task reads:

`TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
ok: [45.56.85.211] => (item=[u'php7.1', u'php7.1-apcu', u'php7.1-cli', u'php7.1-common', u'php7.1-curl', u'php7.1-dev', u'php7.1-fpm', u'php7.1-gd', u'php7.1-imap', u'php7.1-json', u'php7.1-mbstring', u'php7.1-mcrypt', u'php7.1-opcache', u'php7.1-sqlite3', u'php7.1-xml', u'php7.1-yaml'])`

This corresponds to the defaults provided by this role for my platform: https://github.com/geerlingguy/ansible-role-php-versions/blob/master/vars/Debian.yml

The problem appears to be in the set_fact that does not check if the variable exists elsewhere first. 

This is a bit of a problem for database backed sites, since we can't install mysql using the method familiar when only using the php role, and not this role as well.

## Workaround

Instead of overriding the php_packages variable, use php_packages_extra

## Proposed solution

Either document that this role overrides php_packages completely, or split off the set_fact to account for a preexisting definition.

**Comment by yethee** [comment]
What version of Ansible are you using?

This behaviour is valid for Ansible of 2.4.1.0. In 2.4.0.0 or lower local variable is not overridden.

**Comment by socketwench** [comment]
Originally this was on a 2.2 server, but I've since replicated it on 2.4.

**Comment by ArondeParon** [comment]
Just experienced the same issue on Ansible 2.4.

**Comment by yethee** [comment]
This role works correctly for me on Ansible of **2.4.0.0**, when a variable `php_packages` defined in group vars.

```bash
$ ansible --version
ansible 2.4.0.0
  config file = /vagrant/cm/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

```yml
vars:
  php_version: '7.1'
  php_packages:
    - libpcre3-dev
    - "php{{ php_version }}"
    - "php{{ php_version }}-bcmath"
    - "php{{ php_version }}-apcu"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-common"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-dev"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-imap"
    - "php{{ php_version }}-intl"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-mcrypt"
    - "php{{ php_version }}-opcache"
    - "php{{ php_version }}-soap"
    - "php{{ php_version }}-xml"
```

```
TASK [geerlingguy.php-versions : Define PHP variables.] ************************
ok: [default] => (item={'key': u'php_extension_conf_paths', 'value': u'__php_extension_conf_paths'})
ok: [default] => (item={'key': u'php_fpm_daemon', 'value': u'__php_fpm_daemon'})
ok: [default] => (item={'key': u'php_uploadprogress_module_path', 'value': u'__php_uploadprogress_module_path'})
ok: [default] => (item={'key': u'php_xhprof_module_path', 'value': u'__php_xhprof_module_path'})
ok: [default] => (item={'key': u'php_fpm_pool_conf_path', 'value': u'__php_fpm_pool_conf_path'})
ok: [default] => (item={'key': u'php_conf_paths', 'value': u'__php_conf_paths'})
ok: [default] => (item={'key': u'php_xdebug_module_path', 'value': u'__php_xdebug_module_path'})
ok: [default] => (item={'key': u'php_pgsql_package', 'value': u'__php_pgsql_package'})
skipping: [default] => (item={'key': u'php_packages', 'value': u'__php_packages'})
ok: [default] => (item={'key': u'php_mysql_package', 'value': u'__php_mysql_package'})
ok: [default] => (item={'key': u'php_memcached_package', 'value': u'__php_memcached_package'})
ok: [default] => (item={'key': u'php_fpm_conf_path', 'value': u'__php_fpm_conf_path'})
ok: [default] => (item={'key': u'php_tideways_module_path', 'value': u'__php_tideways_module_path'})
ok: [default] => (item={'key': u'php_redis_package', 'value': u'__php_redis_package'})

...

TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
ok: [default] => (item=[u'libpcre3-dev', u'php7.1', u'php7.1-bcmath', u'php7.1-apcu', u'php7.1-cli', u'php7.1-common', u'php7.1-curl', u'php7.1-dev', u'php7.1-gd', u'php7.1-imap', u'php7.1-intl', u'php7.1-json', u'php7.1-mbstring', u'php7.1-mcrypt', u'php7.1-opcache', u'php7.1-soap', u'php7.1-xml'])
```
