### ISSUE TITLE
Php 8.0 install error caused by php-json 

### ISSUE THREAD

**Issue by hedii** [geerlingguy/ansible-role-php-versions#57]
Hi,
This line is problematic when installing php 8.0 on a Debian system : https://github.com/geerlingguy/ansible-role-php-versions/blob/aa60a3d85a82dd2827b534eb8142b3f093d3338b/vars/Debian.yml#L34

php-json is packaged with php 8.0 by default, we get the error: Package 'php8.0-json' has no installation candidate

````
fatal: [monitoring01]: FAILED! => {
    "cache_update_time": 1607244127,
    "cache_updated": false,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "force_apt_get": false,
            "install_recommends": false,
            "name": [
                "php8.0",
                "php8.0-apcu",
                "php8.0-cli",
                "php8.0-common",
                "php8.0-curl",
                "php8.0-dev",
                "php8.0-fpm",
                "php8.0-gd",
                "php8.0-imap",
                "php8.0-json",
                "php8.0-mbstring",
                "php8.0-opcache",
                "php8.0-sqlite3",
                "php8.0-xml",
                "php8.0-yaml"
            ],
            "only_upgrade": false,
            "package": [
                "php8.0",
                "php8.0-apcu",
                "php8.0-cli",
                "php8.0-common",
                "php8.0-curl",
                "php8.0-dev",
                "php8.0-fpm",
                "php8.0-gd",
                "php8.0-imap",
                "php8.0-json",
                "php8.0-mbstring",
                "php8.0-opcache",
                "php8.0-sqlite3",
                "php8.0-xml",
                "php8.0-yaml"
            ],
            "policy_rc_d": null,
            "purge": false,
            "state": "present",
            "update_cache": null,
            "update_cache_retries": 5,
            "update_cache_retry_max_delay": 12,
            "upgrade": null
        }
    },
    "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'php8.0' 'php8.0-apcu' 'php8.0-cli' 'php8.0-common' 'php8.0-curl' 'php8.0-dev' 'php8.0-fpm' 'php8.0-gd' 'php8.0-imap' 'php8.0-json' 'php8.0-mbstring' 'php8.0-opcache' 'php8.0-sqlite3' 'php8.0-xml' 'php8.0-yaml' -o APT::Install-Recommends=no' failed: E: Package 'php8.0-json' has no installation candidate\n",
    "rc": 100,
    "stderr": "E: Package 'php8.0-json' has no installation candidate\n",
    "stderr_lines": [
        "E: Package 'php8.0-json' has no installation candidate"
    ],
    "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nPackage php8.0-json is a virtual package provided by:\n  php8.0-phpdbg 8.0.0-1+0~20201206.6+debian9~1.gbp33744b\n  php8.0-fpm 8.0.0-1+0~20201206.6+debian9~1.gbp33744b\n  php8.0-cli 8.0.0-1+0~20201206.6+debian9~1.gbp33744b\n  php8.0-cgi 8.0.0-1+0~20201206.6+debian9~1.gbp33744b\n  libphp8.0-embed 8.0.0-1+0~20201206.6+debian9~1.gbp33744b\n  libapache2-mod-php8.0 8.0.0-1+0~20201206.6+debian9~1.gbp33744b\n\n",
    "stdout_lines": [
        "Reading package lists...",
        "Building dependency tree...",
        "Reading state information...",
        "Package php8.0-json is a virtual package provided by:",
        "  php8.0-phpdbg 8.0.0-1+0~20201206.6+debian9~1.gbp33744b",
        "  php8.0-fpm 8.0.0-1+0~20201206.6+debian9~1.gbp33744b",
        "  php8.0-cli 8.0.0-1+0~20201206.6+debian9~1.gbp33744b",
        "  php8.0-cgi 8.0.0-1+0~20201206.6+debian9~1.gbp33744b",
        "  libphp8.0-embed 8.0.0-1+0~20201206.6+debian9~1.gbp33744b",
        "  libapache2-mod-php8.0 8.0.0-1+0~20201206.6+debian9~1.gbp33744b",
        ""
    ]
}
````

**Comment by infra-ti-br** [comment]
I stumbled upon this issue when trying to use php-versions role in conjunction with the php role. I tried setting the variable `php_packages: ["php8.0"]` of the php role to get around installing php8.0-json. The problem is that the php_packages is only set in that role if it was not defined before (line 20 task of geerlingguy.php/tasks/main.yml), thus it gets the default __php_packages. And the php_packages variable is defined (conditionally to hostvars) in the php-versions role (line 8 taks of geerlingguy.php-versions/tasks/main.yml).

I circumvent the problem by setting the php_packages between the roles execution:

```yaml
---
- hosts: all
  tasks:
    - name: import php-versions role
      import_role:
        name: geerlingguy.php-versions

    - name: "set php_packages fact to circumvent issue #57"
      set_fact:
        php_packages:
          - php8.0

    - name: import php installation role
      import_role:
        name: geerlingguy.php
```

After that the installation proceeded. Maybe using hostvars is another way to make it work.

I don't have a good proposal to fix. Perhaps the same pattern of the php version role can be used in the php-versions role and set php_packages to __php_packages only if it is not defined before.

**Comment by frock81** [comment]
I stumbled upon this issue when trying to use php-versions role in conjunction with the php role. I tried setting the variable `php_packages: ["php8.0"]` of the php role to get around installing php8.0-json. The problem is that the php_packages is only set in that role if it was not defined before (line 20 task of geerlingguy.php/tasks/main.yml), thus it gets the default __php_packages. And the php_packages variable is defined (conditionally to hostvars) in the php-versions role (line 8 taks of geerlingguy.php-versions/tasks/main.yml).

I circumvent the problem by setting the php_packages between the roles execution:

```yaml
---
- hosts: all
  tasks:
    - name: import php-versions role
      import_role:
        name: geerlingguy.php-versions

    - name: "set php_packages fact to circumvent issue #57"
      set_fact:
        php_packages:
          - php8.0

    - name: import php installation role
      import_role:
        name: geerlingguy.php
```

After that the installation proceeded. Maybe using hostvars is another way to make it work.

I don't have a good proposal to fix. Perhaps the same pattern of the php version role can be used in the php-versions role and set php_packages to __php_packages only if it is not defined before.
