### ISSUE TITLE
[ERROR] Could not find the requested service php7.4-fpm

### ISSUE THREAD

**Issue by alexandruz** [geerlingguy/ansible-role-php-versions#70]
(probably needs a better title.

this only happens when `php_version` is not `8.0`

Setup: 
* vagrant with `box = "debian/buster64"`

_both_ playbooks:
```
  roles:
    - geerlingguy.php-versions
    - geerlingguy.php
```

Playbook 1 - works as _advertised_:
```
  vars:
    php_version: '7.4'
```

Playbook 2 - error from title:
```
  vars:
    php_version: '7.4'
    php_packages:
      - php-cli
      - php-fpm
      - php-zip
      - php-xml
      - php-curl
      - php-ldap
      - php-json
      - php-mbstring
```
I'm not sure if this is related to this role or the php role, due to the fact that the php role is installing _the latest_ php packages.

so, a _combination_ of `php_packages` and the role `php-versions` with a php version other than 8.0 results in a error.
