### ISSUE TITLE
Fails on RHEL 8 when attempting to enable the PowerTools repo

### ISSUE THREAD

**Issue by imgrant** [geerlingguy/ansible-role-php-versions#72]
The task to enable the PowerTools repo (below) does not work on RHEL 8, but it is marked `warn: false` so errors occur later if attempting to install a PHP module that is in powertools.

```yaml
  - name: Enable DNF module for CentOS 8+.
    shell: |
      dnf config-manager --set-enabled powertools
      dnf module enable -y php:remi-{{ php_version }}
    args:
      warn: false
    register: dnf_module_enable
    changed_when: "'Nothing to do' not in dnf_module_enable.stdout"
```
