### ISSUE TITLE
adding modules

### ISSUE THREAD

**Issue by MaxiReglisse** [geerlingguy/ansible-role-php-versions#86]
I'd like to ask a question. I don't understand how you can add modules other than those in the role. Typically, I would need php-pgsql. How do I do this?
I'm sorry to ask this question here, but I couldn't find the answer in the documentation.

thanks in advance,

Ernest.

**Comment by webarchitect609** [comment]
Use variables in `playbook.yml`

```yaml
---
- hosts: localhost

  vars:
    php_install_recommends: false
    php_versions_install_recommends: false
    php_version: "8.2"
    php_packages:
      - "php{{ php_version }}"
      - "php{{ php_version }}-apcu"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-dev"
      - "php{{ php_version }}-json"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-memcache"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-xdebug"
      - "php{{ php_version }}-xml"
      - "memcached"

  roles:
    - role: geerlingguy.php-versions
```
